### ISSUE TITLE
Genome Meta-Data Classes need string literals

### ISSUE THREAD

**Issue by drew111b** [superphy/semantic#24]
Some URI classes in Blazegraph are created with the data in the URI: (For example - <https://github.com/superphy#O148>) They do not have any associated literal data to pull for referencing outside of blaze-graph.
For instance, meta data has the following classes without data attached:
Serotype_O
Serotype_H
Host (both Latin and English)
Etc

**Comment by Helisquinde** [comment]
If we use rdfs:label it may not be necessary to modify the ontology, only the metadata uploader script.

**Comment by drew111b** [comment]
Looks like just the serotype_O and Serotype_H uri needs to link to literal.
example
<https://github.com/superphy#OUnknown> ""
<https://github.com/superphy#O149> "O149"
<https://github.com/superphy#H4> "H4"
This would be changed in uploader module.

**Comment by Helisquinde** [comment]
Added rdfs:label for the indicated classes. IDs will be composed of only numerics for now and changed if necessary.
